package karazin.scala.users.group.week9.homework

/*

  Write test for a compound functors
  Implemented tests with autogenerated values

  The test implementation is tricky
  and for now there is no good solution
  but try to do your best

 */

import scala.concurrent.Future
import scala.concurrent.ExecutionContext.Implicits.global

import cats.Functor
import cats.implicits._

import munit.ScalaCheckSuite
import org.scalacheck.Prop._

import karazin.scala.users.group.week9.homework.functors._


class FunctorsSuite extends ScalaCheckSuite:

  property("successful test example") {
    forAll { (int: Int) =>
      int == int
    }
  }
